name: GitHub Actions Demo
run-name: ${{ github.actor }} is running tests
on:
  pull_request:
    branches: [master]
jobs:
  testApp:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Unit test
        run: npm test-ci

      - name: Install playwright
        run: npx playwright install --with-deps chromium

      - name: e2e test
        run: npm run e2e-ci

      - name: Build App
        run: npm run build
